spring.datasource.url=jdbc:postgresql://localhost:5432/ingressos
spring.datasource.username=postgres
spring.datasource.password=samira01

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081